In [5]:
import torch

In [1]:
import numpy as np

Training Data

In [2]:
# Input ( Temperature, Rainfall, Humidity)
inputs=np.array([[73,67,43],[91,88,64],[87,134,58],[102,43,37],[69,96,70]], dtype='float32')

In [3]:
# Targets (Apples, Oranges)
targets=np.array([[56,70],[81,101],[119,133],[22,37],[103,119]], dtype='float32')

In [6]:
# Convert inputs and targets to tensors
inputs=torch.from_numpy(inputs)
targets=torch.from_numpy(targets)
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


Weight and baises

In [8]:
w=torch.randn(2,3, requires_grad=True)
b=torch.randn(2, requires_grad=True)
print(w,'\n',b)

tensor([[ 0.9448, -1.6768,  1.0852],
        [ 1.0040, -1.1812, -0.3691]], requires_grad=True) 
 tensor([0.5312, 1.2475], requires_grad=True)


In [9]:
def model(x):
    return x @ w.t()+b

@ represent matreix multiplication in PyTorch and .t method returns the transpose of a tensor.

In [10]:
preds =model(inputs)
preds

tensor([[  3.8205, -20.4737],
        [  8.4035, -34.9590],
        [-79.0211, -91.0966],
        [ 64.9530,  39.2075],
        [-19.2860, -68.7123]], grad_fn=<AddBackward0>)

In [11]:
# compare preds with targets
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


Loss Function

In [12]:
# Mean Square Error Loss
def msel(t1,t2):
    dif=t1-t2
    return torch.sum(dif*dif)/dif.numel()

In [13]:
loss=msel(preds,targets)
print(loss)

tensor(17613.4531, grad_fn=<DivBackward0>)


Compute Gradients

In [ ]:
loss.backward()
# Gradients for weights
print(w)
print(w.grad)

Adjust weights and biases to reduce the loss

In [15]:
w
w.grad

tensor([[ -6339.9487,  -9262.3643,  -5069.1753],
        [-10240.0469, -13196.1055,  -7729.5059]])

In [16]:
with torch.no_grad():
    w-=w.grad*1e-5
    b-=b.grad*1e-5

In [17]:
# Verify Loss is Lower
loss=msel(preds, targets)
print(loss)

tensor(17613.4531, grad_fn=<DivBackward0>)


In [18]:
w.grad.zero_()
b.grad.zero_()
print(w.grad, '\n', b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) 
 tensor([0., 0.])


Train the Model using Gradient Descent

In [19]:
# Generate Predictions
preds=model(inputs)
print(preds)

tensor([[ 16.8350,  -0.8321],
        [ 25.5689,  -9.0798],
        [-58.1529, -60.0206],
        [ 77.2790,  58.1879],
        [ -2.4703, -43.5665]], grad_fn=<AddBackward0>)


In [20]:
# Calculate the loss
loss= msel(preds, targets)
print(loss)

tensor(13143.7891, grad_fn=<DivBackward0>)


In [21]:
# Compute Gradients
loss.backward()
print(w.grad)
print(b.grad)

tensor([[ -4990.9150,  -7797.7266,  -4168.8311],
        [ -8207.3457, -10998.5684,  -6376.3579]])
tensor([ -64.3881, -103.0622])


In [23]:
# Adjust the weights & Reset Gradients
with torch.no_grad():
    w-=w.grad*1e-5
    b-=b.grad*1e-5
    w.grad.zero_()
    b.grad.zero_()

In [24]:
print(w)
print(b)

tensor([[ 1.0581, -1.5062,  1.1776],
        [ 1.1885, -0.9393, -0.2281]], requires_grad=True)
tensor([0.5333, 1.2508], requires_grad=True)


In [25]:
# Calculate the Loss
preds=model(inputs)
loss=msel(preds, targets)
print(loss)

tensor(10115.7803, grad_fn=<DivBackward0>)


Train for multiple epochs

In [26]:
# Train for 100 epochs
for i in range(100):
    preds=model(inputs)
    loss=msel(preds, targets)
    loss.backward()
    with torch.no_grad():
        w-=w.grad*1e-5
        b-=b.grad*1e-5
        w.grad.zero_()
        b.grad.zero_()

In [27]:
# Claculate the Loss
preds=model(inputs)
loss=msel(preds, targets)
print(loss)

tensor(1150.2048, grad_fn=<DivBackward0>)


In [28]:
# predictions
preds

tensor([[ 67.3898,  80.8668],
        [ 96.5920, 103.5685],
        [ 69.5409, 109.3976],
        [ 80.7466,  96.7357],
        [ 92.2320,  89.5760]], grad_fn=<AddBackward0>)

In [29]:
# Targets
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

Linear Regrerssion using PyTorch built-ins

In [30]:
from torch import nn

In [32]:
#Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70],
[74, 66, 43],
[91, 87, 65],
[88, 134, 59],
[101, 44, 37],
[68, 96, 71],
[73, 66, 44],
[92, 87, 64],
[87, 135, 57],
[103, 43, 36],
[68, 97, 70]],
dtype='float32')
# Targets (apples, oranges)
targets = np.array([[56, 70],
[81, 101],
[119, 133],
[22, 37],
[103, 119],
[57, 69],
[80, 102],
[118, 132],
[21, 38],
[104, 118],
[57, 69],
[82, 100],
[118, 134],
[20, 38],
[102, 120]],
dtype='float32')
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

Dataset and DataLoader

In [33]:
from torch.utils.data import TensorDataset

In [34]:
train_ds=TensorDataset(inputs, targets)

In [35]:
train_ds[0:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [36]:
from torch.utils.data import DataLoader

In [37]:
# Define a DataLoader
b_size=5
train_dl=DataLoader(train_ds, b_size,shuffle=True)

In [38]:
for x, y in train_dl:
    print(x)
    print(y)
    break

tensor([[ 88., 134.,  59.],
        [ 91.,  88.,  64.],
        [ 74.,  66.,  43.],
        [ 68.,  97.,  70.],
        [ 73.,  66.,  44.]])
tensor([[118., 132.],
        [ 81., 101.],
        [ 57.,  69.],
        [102., 120.],
        [ 57.,  69.]])


Neural Network (nn.Linear)

In [39]:
model=nn.Linear(3,2)
print(model.weight,'\n',model.bias)

Parameter containing:
tensor([[ 0.2505,  0.1529, -0.2450],
        [ 0.3334,  0.2828,  0.1070]], requires_grad=True) 
 Parameter containing:
tensor([-0.2891,  0.0671], requires_grad=True)


In [40]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.2505,  0.1529, -0.2450],
         [ 0.3334,  0.2828,  0.1070]], requires_grad=True),
 Parameter containing:
 tensor([-0.2891,  0.0671], requires_grad=True)]

In [41]:
# Generate Predictions
preds=model(inputs)
preds

tensor([[17.7083, 47.9541],
        [20.2838, 62.1410],
        [27.7834, 73.1735],
        [22.7749, 50.1945],
        [14.5251, 57.7099],
        [17.8060, 48.0047],
        [19.8860, 61.9652],
        [27.7890, 73.6139],
        [22.6772, 50.1439],
        [14.0296, 57.4835],
        [17.3105, 47.7783],
        [20.3815, 62.1916],
        [28.1813, 73.3493],
        [23.2704, 50.4210],
        [14.4275, 57.6593]], grad_fn=<AddmmBackward0>)

Loss Function

In [42]:
# importing nn.Functional
import torch.nn.functional as f

In [43]:
# Define Loss Function
loss_fn=f.mse_loss
loss=loss_fn(model(inputs),targets)
loss

tensor(3072.4385, grad_fn=<MseLossBackward0>)

Optimizer ( optim.SGD) SGD: Stochastic Gradient Descent

In [45]:
# Define Optimizer
opt=torch.optim.SGD(model.parameters(),lr=1e-5)

Utility Function (fit)

In [49]:
def fit(model, loss_fn, num_epochs, opt, train_dl):
    # Repeat
    for epoch in range(num_epochs):
        # train
        for x, y, in train_dl:
            #1. Generate Predictions
            preds=model(x)
            #2. Loss Calculation
            loss=loss_fn(preds,y)
            #3. Gradient Computation
            loss.backward()
            #4. Update Parameters
            opt.step()
            #5. Reset Gradient
            opt.zero_grad()
            
        # Print
        if (epoch+1)%10==0:
            print('Epoch [{}/{}],Loss: {:4f}'.format(epoch+1,num_epochs,loss.item()))
            

In [50]:
fit(model,loss_fn,100,opt,train_dl)

Epoch [10/100],Loss: 736.886963
Epoch [20/100],Loss: 390.318054
Epoch [30/100],Loss: 164.804092
Epoch [40/100],Loss: 140.442657
Epoch [50/100],Loss: 192.882950
Epoch [60/100],Loss: 116.044601
Epoch [70/100],Loss: 133.888397
Epoch [80/100],Loss: 52.185112
Epoch [90/100],Loss: 57.694916
Epoch [100/100],Loss: 45.344902


In [51]:
preds=model(inputs)
preds

tensor([[ 58.4753,  71.7785],
        [ 79.1484,  97.9802],
        [122.3125, 136.5550],
        [ 29.5569,  45.2475],
        [ 91.6856, 109.6785],
        [ 57.3533,  70.8009],
        [ 78.3874,  97.5293],
        [122.3245, 136.9021],
        [ 30.6788,  46.2251],
        [ 92.0465, 110.2052],
        [ 57.7143,  71.3276],
        [ 78.0264,  97.0026],
        [123.0735, 137.0058],
        [ 29.1959,  44.7209],
        [ 92.8075, 110.6561]], grad_fn=<AddmmBackward0>)

In [52]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])

In [53]:
model(torch.tensor([[75,63,44.]]))

tensor([[54.5228, 68.4848]], grad_fn=<AddmmBackward0>)